Traceback (most recent call last):
  File "third_party/my_run_tag.py", line 17, in <module>
    """Fine-tuning models for NER and POS tagging."""
KeyboardInterrupt
Command exited with non-zero status 1
0.02user 0.00system 0:00.03elapsed 100%CPU (0avgtext+0avgdata 12524maxresident)k
0inputs+8outputs (0major+1871minor)pagefaults 0swaps
Command terminated by signal 2
0.00user 0.00system 0:00.00elapsed 100%CPU (0avgtext+0avgdata 6512maxresident)k
0inputs+0outputs (0major+488minor)pagefaults 0swaps
Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.6/site.py", line 570, in <module>
    main()
  File "/usr/lib/python3.6/site.py", line 553, in main
    known_paths = venv(known_paths)
  File "/usr/lib/python3.6/site.py", line 490, in venv
    addsitepackages(known_paths, [sys.prefix])
  File "/usr/lib/python3.6/site.py", line 345, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/usr/lib/python3.6/site.py", line 213, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/usr/lib/python3.6/site.py", line 174, in addpackage
    exec(line)
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/types.py", line 171, in <module>
    import functools as _functools
  File "/usr/lib/python3.6/functools.py", line 21, in <module>
    from collections import namedtuple
  File "/usr/lib/python3.6/collections/__init__.py", line 26, in <module>
    from operator import itemgetter as _itemgetter, eq as _eq
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 779, in get_code
  File "<frozen importlib._bootstrap_external>", line 487, in _compile_bytecode
KeyboardInterrupt
Command exited with non-zero status 1
0.02user 0.00system 0:00.02elapsed 100%CPU (0avgtext+0avgdata 8948maxresident)k
0inputs+0outputs (0major+944minor)pagefaults 0swaps
Command terminated by signal 2
0.00user 0.00system 0:00.00elapsed 100%CPU (0avgtext+0avgdata 6460maxresident)k
0inputs+0outputs (0major+469minor)pagefaults 0swaps
Traceback (most recent call last):
  File "third_party/my_run_tag.py", line 26, in <module>
    from dataclasses import dataclass, field
  File "/home/abhijeet/rohan/venvs/cloud-emea-copy/lib/python3.6/site-packages/dataclasses.py", line 5, in <module>
    import inspect
  File "/usr/lib/python3.6/inspect.py", line 2572, in <module>
KeyboardInterrupt
Command exited with non-zero status 1
0.05user 0.01system 0:00.07elapsed 98%CPU (0avgtext+0avgdata 15072maxresident)k
0inputs+0outputs (0major+2469minor)pagefaults 0swaps
Failed to import the site module
Traceback (most recent call last):
  File "/usr/lib/python3.6/site.py", line 79, in <module>
    import os
  File "/usr/lib/python3.6/os.py", line 51, in <module>
    from posix import *
KeyboardInterrupt
Command exited with non-zero status 1
0.02user 0.00system 0:00.02elapsed 100%CPU (0avgtext+0avgdata 7984maxresident)k
0inputs+0outputs (0major+723minor)pagefaults 0swaps
